version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    executor: python/default
    working_directory: ~/src
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.txt
      - run:
          name: Run Code Checks
          command: |
            black . -l 79
            pylint *.py
            flake8 .
            bandit -r .

workflows:
  main:
    jobs:
      - build
